"""Immutable DecisionArtifact model with SHA-256 canonical input hashing (TICKET-16).

Architecture Baseline: Frozen Architecture Baseline v11.
Enforces:
- INV-01: AI recommends; it does not execute (Recommendation-only artifact).
- INV-17: Immutable Decision Artifacts with SHA-256 canonical input snapshot hashing.
- Deep payload and parameter immutability via ImmutableDict.
- Strict input validation and fail-closed handling for blocked/non-recoverable cases.
"""

from datetime import datetime, timezone
import hashlib
from typing import Any, Dict, Mapping, Optional
import uuid
from pydantic import ConfigDict, Field, field_validator

from src.revenue_recovery.foundation.audit import (
    ImmutableDict,
    canonical_json,
    freeze_payload,
)
from src.revenue_recovery.foundation.events import (
    ActionChannel,
    ActionType,
    CaseState,
    ImmutableBaseModel,
    RecoveryCase,
    RiskTier,
)
from src.revenue_recovery.recovery_engine.diagnosis import DiagnosisResult


def _to_str_val(val: Any) -> str:
    """Safely extracts the string representation of an enum or string."""
    if hasattr(val, "value"):
        return str(val.value)
    return str(val)


def compute_canonical_input_hash(input_snapshot: Mapping[str, Any] | dict[str, Any]) -> str:
    """
    Computes a deterministic SHA-256 digest over the canonical JSON serialization of input_snapshot.
    Enforces INV-17 (Immutable Decision Artifacts with input snapshot hashes).
    """
    canonical_str = canonical_json(input_snapshot)
    return hashlib.sha256(canonical_str.encode("utf-8")).hexdigest()


class DecisionArtifact(ImmutableBaseModel):
    """
    Authoritative, immutable decision record generated by the AI Decision Engine.
    Represents an advisory action recommendation without execution authority.
    """
    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
        arbitrary_types_allowed=True,
    )

    artifact_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    case_id: str = Field(min_length=1)
    model_version: str = Field(min_length=1)
    prompt_version: str = Field(min_length=1)
    tool_schema_version: str = Field(min_length=1)
    canonical_input_hash: str = Field(min_length=64, max_length=64)
    input_snapshot: ImmutableDict
    recommended_action: ActionType
    parameters: ImmutableDict
    confidence_score: float = Field(ge=0.0, le=1.0)
    reasoning_summary: str = Field(min_length=1)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @field_validator("canonical_input_hash")
    @classmethod
    def validate_hash_format(cls, v: str) -> str:
        v_lower = v.lower()
        if len(v_lower) != 64 or not all(c in "0123456789abcdef" for c in v_lower):
            raise ValueError("canonical_input_hash must be a valid 64-character lowercase hex string")
        return v_lower

    @field_validator("input_snapshot", "parameters", mode="before")
    @classmethod
    def deep_freeze_mappings(cls, v: Any) -> ImmutableDict:
        if not isinstance(v, (dict, Mapping, ImmutableDict)):
            raise ValueError("Mapping field must be a dictionary or mapping")
        return freeze_payload(v) if not isinstance(v, ImmutableDict) else v


class DecisionArtifactCreatedEvent(ImmutableBaseModel):
    """Domain event emitted upon successful generation of an immutable DecisionArtifact."""
    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    artifact_id: str = Field(min_length=1)
    case_id: str = Field(min_length=1)
    canonical_input_hash: str = Field(min_length=64, max_length=64)
    model_version: str = Field(min_length=1)
    recommended_action: ActionType
    occurred_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


def create_decision_artifact(
    case: RecoveryCase,
    diagnosis: DiagnosisResult,
    model_version: str = "mock-decision-v1.0.0",
    prompt_version: str = "v1.0.0",
    tool_schema_version: str = "v1.0.0",
    override_reasoning: Optional[str] = None,
) -> DecisionArtifact:
    """
    Constructs a valid, immutable DecisionArtifact from an active RecoveryCase and DiagnosisResult.
    Enforces deterministic canonical input hashing and safety routing.
    """
    # Guard: Case must be in an evaluable state
    case_state_str = _to_str_val(case.state)
    if case_state_str not in {CaseState.DIAGNOSED.value, CaseState.EVALUATING.value}:
        raise ValueError(
            f"Cannot create DecisionArtifact for case '{case.case_id}' in state '{case.state}'. "
            f"Expected DIAGNOSED or EVALUATING."
        )

    channel_str = _to_str_val(diagnosis.recommended_channel)
    risk_tier_str = _to_str_val(case.risk_tier)

    # Construct deterministic input snapshot
    input_snapshot_dict = {
        "case_id": case.case_id,
        "customer_id": case.customer_id,
        "amount_in_cents": case.amount_in_cents,
        "currency": case.currency,
        "state": case_state_str,
        "risk_tier": risk_tier_str,
        "attempt_count": case.attempt_count,
        "max_attempts": case.max_attempts,
        "diagnosis": {
            "diagnosis_code": diagnosis.diagnosis_code,
            "risk_score": diagnosis.risk_score,
            "risk_tier": _to_str_val(diagnosis.risk_tier),
            "is_recoverable": diagnosis.is_recoverable,
            "recommended_channel": channel_str,
        },
    }

    # Compute deterministic SHA-256 canonical input hash (INV-17)
    canonical_hash = compute_canonical_input_hash(input_snapshot_dict)

    # Determine recommended action and parameters based on diagnosis
    if risk_tier_str == RiskTier.BLOCKED.value or not diagnosis.is_recoverable:
        recommended_action = ActionType.NO_ACTION
        parameters = {
            "channel": ActionChannel.INTERNAL_SYSTEM.value,
            "reason": "Recovery blocked by safety or fraud risk",
            "amount_in_cents": 0,
            "currency": case.currency,
        }
        confidence_score = 1.0000
        reasoning = override_reasoning or "Case classified as BLOCKED or non-recoverable; no recovery action recommended."
    elif channel_str == ActionChannel.DIRECT_PAYMENT_GATEWAY.value:
        recommended_action = ActionType.RETRY_CHARGE
        parameters = {
            "channel": ActionChannel.DIRECT_PAYMENT_GATEWAY.value,
            "amount_in_cents": case.amount_in_cents,
            "currency": case.currency,
            "suggested_retry_delay_seconds": 3600,
        }
        confidence_score = round(1.0 - diagnosis.risk_score, 4)
        reasoning = override_reasoning or f"Automated payment retry recommended via {channel_str}."
    else:
        recommended_action = ActionType.SEND_NOTIFICATION
        parameters = {
            "channel": channel_str,
            "amount_in_cents": case.amount_in_cents,
            "currency": case.currency,
            "template_id": f"tpl_{diagnosis.diagnosis_code.lower()}",
        }
        confidence_score = round(1.0 - diagnosis.risk_score, 4)
        reasoning = override_reasoning or f"Customer notification recommended via {channel_str}."

    return DecisionArtifact(
        case_id=case.case_id,
        model_version=model_version,
        prompt_version=prompt_version,
        tool_schema_version=tool_schema_version,
        canonical_input_hash=canonical_hash,
        input_snapshot=input_snapshot_dict,
        recommended_action=recommended_action,
        parameters=parameters,
        confidence_score=confidence_score,
        reasoning_summary=reasoning,
    )
